### ISSUE TITLE
[Bug]: regularly (often once a day) i get several warnings 

### ISSUE THREAD

**Issue by marlan99** [iobroker-community-adapters/ioBroker.chromecast#149] opened 2023-01-03 16:56 UTC
### What happened?

most often during the night between 02:00 - 05:00 i get some warnings but there will be no script running and also no restart of the instance is configured.
no clue why this happens

chromecast.0 | 2023-01-03 04:57:43.177 | warn | Wohnzimmer - Client error: Error: read ECONNRESET at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
-- | -- | -- | --
chromecast.0 | 2023-01-03 04:57:42.167 | warn | Wohnzimmer - Client error: Error: read ECONNRESET at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
chromecast.0 | 2023-01-03 04:57:42.162 | warn | Wohnzimmer - Client error: Error: read ECONNRESET at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
chromecast.0 | 2023-01-03 04:57:35.615 | warn | Wohnzimmer - Client error: Error: connect ECONNREFUSED 192.168.1.117:8009 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
chromecast.0 | 2023-01-03 04:57:35.612 | warn | Wohnzimmer - Client error: Error: connect ECONNREFUSED 192.168.1.117:8009 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
chromecast.0 | 2023-01-03 04:57:33.609 | warn | Wohnzimmer - Client error: Error: connect ECONNREFUSED 192.168.1.117:8009 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
chromecast.0 | 2023-01-03 04:57:33.605 | warn | Wohnzimmer - Client error: Error: connect ECONNREFUSED 192.168.1.117:8009 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
chromecast.0 | 2023-01-03 04:57:32.601 | warn | Wohnzimmer - Client error: Error: connect ECONNREFUSED 192.168.1.117:8009 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
chromecast.0 | 2023-01-03 04:57:32.598 | warn | Wohnzimmer - Client error: Error: connect ECONNREFUSED 192.168.1.117:8009 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
chromecast.0 | 2023-01-03 04:57:31.514 | warn | Wohnzimmer - Client error: Error: Device timeout at fn.ontimeout (/opt/iobroker/node_modules/castv2-client/lib/senders/platform.js:56:26) at Object.onceWrapper (node:events:627:28) at fn.emit (node:events:513:28) at fn.emit (node:domain:489:12) at Timeout.ontimeout [as _onTimeout] (/opt/iobroker/node_modules/castv2-client/lib/controllers/heartbeat.js:44:10) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
chromecast.0 | 2023-01-03 04:57:31.510 | warn | Wohnzimmer - Client error: Error: Device timeout at fn.ontimeout (/opt/iobroker/node_modules/castv2-client/lib/senders/platform.js:56:26) at Object.onceWrapper (node:events:627:28) at fn.emit (node:events:513:28) at fn.emit (node:domain:489:12) at Timeout.ontimeout [as _onTimeout] (/opt/iobroker/node_modules/castv2-client/lib/controllers/heartbeat.js:44:10) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
chromecast.0 | 2023-01-03 04:17:46.880 | warn | Gäste WC - Client error: Error: read ECONNRESET at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
chromecast.0 | 2023-01-03 04:17:45.866 | warn | Gäste WC - Client error: Error: read ECONNRESET at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
chromecast.0 | 2023-01-03 04:17:33.705 | warn | Gäste WC - Client error: Error: Device timeout at fn.ontimeout (/opt/iobroker/node_modules/castv2-client/lib/senders/platform.js:56:26) at Object.onceWrapper (node:events:627:28) at fn.emit (node:events:513:28) at fn.emit (node:domain:489:12) at Timeout.ontimeout [as _onTimeout] (/opt/iobroker/node_modules/castv2-client/lib/controllers/heartbeat.js:44:10) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
chromecast.0 | 2023-01-03 03:23:57.661 | warn | Wintergarten - Client error: Error: read ECONNRESET at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
chromecast.0 | 2023-01-03 03:23:57.645 | warn | Wintergarten - Client error: Error: read ECONNRESET at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
chromecast.0 | 2023-01-03 03:23:51.891 | warn | Wintergarten - Client error: Error: connect ECONNREFUSED 192.168.1.110:8009 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
chromecast.0 | 2023-01-03 03:23:50.574 | warn | Wintergarten - Client error: Error: connect ECONNREFUSED 192.168.1.110:8009 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
chromecast.0 | 2023-01-03 03:23:49.683 | warn | Wintergarten - Client error: Error: connect ECONNREFUSED 192.168.1.110:8009 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
chromecast.0 | 2023-01-03 03:23:48.678 | warn | Wintergarten - Client error: Error: connect ECONNREFUSED 192.168.1.110:8009 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
chromecast.0 | 2023-01-03 03:23:48.565 | warn | Wintergarten - Client error: Error: connect ECONNREFUSED 192.168.1.110:8009 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
chromecast.0 | 2023-01-03 03:23:47.559 | warn | Wintergarten - Client error: Error: connect ECONNREFUSED 192.168.1.110:8009 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
chromecast.0 | 2023-01-03 03:23:46.539 | warn | Wintergarten - Client error: Error: Device timeout at fn.ontimeout (/opt/iobroker/node_modules/castv2-client/lib/senders/platform.js:56:26) at Object.onceWrapper (node:events:627:28) at fn.emit (node:events:513:28) at fn.emit (node:domain:489:12) at Timeout.ontimeout [as _onTimeout] (/opt/iobroker/node_modules/castv2-client/lib/controllers/heartbeat.js:44:10) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
chromecast.0 | 2023-01-03 03:23:45.552 | warn | Wintergarten - Client error: Error: Device timeout at fn.ontimeout (/opt/iobroker/node_modules/castv2-client/lib/senders/platform.js:56:26) at Object.onceWrapper (node:events:627:28) at fn.emit (node:events:513:28) at fn.emit (node:domain:489:12) at Timeout.ontimeout [as _onTimeout] (/opt/iobroker/node_modules/castv2-client/lib/controllers/heartbeat.js:44:10) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
chromecast.0 | 2023-01-03 02:02:37.176 | warn | Büro - Client error: Error: read ECONNRESET at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
chromecast.0 | 2023-01-03 02:02:36.167 | warn | Büro - Client error: Error: read ECONNRESET at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
chromecast.0 | 2023-01-03 02:02:36.162 | warn | Büro - Client error: Error: read ECONNRESET at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
chromecast.0 | 2023-01-03 02:02:29.714 | warn | Büro - Client error: Error: connect ECONNREFUSED 192.168.1.134:8009 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
chromecast.0 | 2023-01-03 02:02:29.527 | warn | Büro - Client error: Error: connect ECONNREFUSED 192.168.1.134:8009 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
chromecast.0 | 2023-01-03 02:02:27.710 | warn | Büro - Client error: Error: connect ECONNREFUSED 192.168.1.134:8009 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
chromecast.0 | 2023-01-03 02:02:27.523 | warn | Büro - Client error: Error: connect ECONNREFUSED 192.168.1.134:8009 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
chromecast.0 | 2023-01-03 02:02:26.704 | warn | Büro - Client error: Error: connect ECONNREFUSED 192.168.1.134:8009 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
chromecast.0 | 2023-01-03 02:02:26.698 | warn | Büro - Client error: Error: Device timeout at fn.ontimeout (/opt/iobroker/node_modules/castv2-client/lib/senders/platform.js:56:26) at Object.onceWrapper (node:events:627:28) at fn.emit (node:events:513:28) at fn.emit (node:domain:489:12) at Timeout.ontimeout [as _onTimeout] (/opt/iobroker/node_modules/castv2-client/lib/controllers/heartbeat.js:44:10) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
chromecast.0 | 2023-01-03 02:02:26.518 | warn | Büro - Client error: Error: connect ECONNREFUSED 192.168.1.134:8009 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
chromecast.0 | 2023-01-03 02:02:23.341 | warn | Büro - Client error: Error: Device timeout at fn.ontimeout (/opt/iobroker/node_modules/castv2-client/lib/senders/platform.js:56:26) at Object.onceWrapper (node:events:627:28) at fn.emit (node:events:513:28) at fn.emit (node:domain:489:12) at Timeout.ontimeout [as _onTimeout] (/opt/iobroker/node_modules/castv2-client/lib/controllers/heartbeat.js:44:10) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)

### Adapter Version

3.1.0

### JS-Controller Version

4.0.23

### Node JS Version

16.18.1

### NPM Version

8.19.2

### Operating System

Debian

**Comment by Berchemer** [comment] 2023-01-04 10:28
Similar warnings reularly between 03:00 am and 05:00 am here as well.

**Comment by raintonr** [comment] 2023-05-26 05:48
Duplicate of #162

**Closed by raintonr** 2023-05-26 05:48 UTC
Labels: bug
