### ISSUE TITLE
[Bug]: host is null in play url

### ISSUE THREAD

**Issue by divY42** [iobroker-community-adapters/ioBroker.chromecast#150] opened 2023-01-12 14:36 UTC
### Contact Details

github@alexanderolbricht.de

### What happened?

I recently reinstalled the chromecast adapter to be able to send notifications to my chromecast devices in conjunction with tts adapter "sayit". Although working in the past, currently I run into an "getaddrinfo" error because my host is null.

![image](https://user-images.githubusercontent.com/47355195/211417953-6f1979f0-97c4-4d23-a9cf-ba35238c9205.png)

adapter.config.webServer seems to be null. Using a second web server instance does nothing for me.
I cannot edit or select a proper IP adress in the chromecast adapter settings.

![image](https://user-images.githubusercontent.com/47355195/211417548-d624d4d0-ba54-4b7f-a16e-e785b31454c4.png)

This is the configuration for my web.0 instance:

![image](https://user-images.githubusercontent.com/47355195/211417676-59a4a8f8-4cfd-49db-a16f-4efc63afcef1.png)

Any ideas what I can try to get rid of this error?
discovery and net-tools are running as well.

### Adapter Version

3.0.3

### JS-Controller Version

4.0.24

### Node JS Version

18.1.0

### NPM Version

8.8.0

### Operating System

Ubuntu

**Comment by raintonr** [comment] 2023-01-12 14:37
Ah... in fact... I think this is a duplicate of #145. Sorry I didn't notice that earlier. Doh!

**Closed by raintonr** 2023-01-12 14:37 UTC
Labels: bug

**Comment by divY42** [comment] 2023-01-12 16:25
Sorry for the question, but how exactly do I do that? Never done that before.
I know I am supposed to go into expert mode and use the Octocat icon, but what URL do I provide there?

Neither

https://github.com/iobroker-community-adapters/ioBroker.chromecast/tree/master

nor

https://github.com/iobroker-community-adapters/ioBroker.chromecast

is working for me.

![image](https://user-images.githubusercontent.com/47355195/212123731-68ca285c-3d40-4c9f-9ecc-43190ea3e726.png)

**Comment by raintonr** [comment] 2023-01-12 16:44
Doh! There was a typo in the package.json. Fixed now so please try again.

FYI, I just fixed #145 so with any luck your issue will have magically disappeared :wink:

**Comment by divY42** [comment] 2023-01-12 17:18
Sadly, your fix doesn't work for me.

Even with 3.1.0, I cannot select an IP adress from my web instance.

![image](https://user-images.githubusercontent.com/47355195/212135246-60f0ffdd-84b4-4cbf-9618-6b26d636fbe3.png)

**Comment by raintonr** [comment] 2023-01-13 06:08
Please forget the versions and use the latest installed directly from GitHub master so we can troubleshoot this.

What does the admin screen now show? Can you now select an IP address? If you can select an IP address, is it getting saved properly (look in system.adapter.chromecast.0 object for the native property). If it's getting saved properly, what is the URL that is being shown when you try and play a local file?

**Comment by divY42** [comment] 2023-01-13 15:33
I did use the latest installed directly from GitHub.
At least I think that's what I did.

I used https://github.com/iobroker-community-adapters/ioBroker.chromecast/tree/master and installed it via adapter view in ioBroker

![image](https://user-images.githubusercontent.com/47355195/212357786-c837f09c-d2a0-426f-ae8d-acdbf115b031.png)

After that, I logged onto my ubuntu host and did iobroker add ioBroker.chromecast, which resulted in an instance with version 3.1.0.
Did I do something wrong?

Besides that, no, I Still cannot select an IP address:

![image](https://user-images.githubusercontent.com/47355195/212358119-403ccb47-f83c-411d-9b00-a11ff301b398.png)

**Comment by raintonr** [comment] 2023-01-13 16:23
Maybe the upload didn't run or failed? You could run `iob upload chromecast` and check again.

If still not working, please look at the source of the Chromecast admin page...

http(s)://your.iob.host/adapter/chromecast/index_m.html?0&newReact=true&0&react=colored

... and check it is the same as Github. Particularly line that the hidden option on line 119 is there: https://github.com/iobroker-community-adapters/ioBroker.chromecast/blob/master/admin/index_m.html#L119

**Comment by divY42** [comment] 2023-01-13 17:18
yes, my page source code looks exactly the same like in https://github.com/iobroker-community-adapters/ioBroker.chromecast/blob/master/admin/index_m.html#L119

![image](https://user-images.githubusercontent.com/47355195/212380048-5b1910a0-a414-4ffb-a264-50975da6e924.png)

**Comment by raintonr** [comment] 2023-01-13 19:04
I notice you are using web 5.4.1. I am still on 4.3.0 here. Maybe the newer adapter isn't storing the value as expected?

What is the bind value on your web config? The admin screen shows `0.0.0.0` but I wonder if that's not actually what is stored.

Please turn on expert mode and check what value exactly has been stored. I would expect `0.0.0.0` but maybe this is just a blank string?

![image](https://user-images.githubusercontent.com/3794098/212398561-74ee5e55-f550-4b2d-82ec-7762793313d5.png)
